import {
    Activity,
    Briefcase,
    CheckSquare,
    Code,
    CreditCard,
    DollarSign,
    FileText,
    Gift,
    GraduationCap,
    Heart,
    Home,
    MessageCircle,
    ShoppingBag,
    ShoppingCart,
    Star,
    Tag,
    Users,
    Plane,
    Music,
    Book,
    Camera,
    Video,
    Mail,
    PenSquare,
    Globe,
    Server,
    Cloud,
    Compass,
    Settings,
    Bell,
    Archive,
    Trash2,
    Palette,
    BriefcaseBusiness,
    List,
    type LucideIcon,
  } from 'lucide-react';
  
  export const iconLibrary: { [key: string]: LucideIcon } = {
    Activity,
    Briefcase,
    CheckSquare,
    Code,
    CreditCard,
    DollarSign,
    FileText,
    Gift,
    GraduationCap,
    Heart,
    Home,
    MessageCircle,
    ShoppingBag,
    ShoppingCart,
    Star,
    Tag,
    Users,
    Plane,
    Music,
    Book,
    Camera,
    Video,
    Mail,
    PenSquare,
    Globe,
    Server,
    Cloud,
    Compass,
    Settings,
    Bell,
    Palette,
    BriefcaseBusiness,
    List,
  };
  
  export const iconNames = Object.keys(iconLibrary);
  
  export const getIcon = (name: string): LucideIcon => {
    return iconLibrary[name] || FileText;
  };
  